[package]
name = "os"
version = "0.0.1"
edition = "2021"
authors = ["Chuan Wang"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sbi-rt = {version = "0.0.2", features = ["legacy"]}